export const TRANSACTION_LIST_REQUEST = 'TRANSACTION_LIST_REQUEST'
export const TRANSACTION_LIST_SUCCESS = 'TRANSACTION_LIST_SUCCESS'
export const TRANSACTION_LIST_FAIL = 'TRANSACTION_LIST_FAIL'

export const TRANSACTION_ADD_REQUEST = 'TRANSACTION_ADD_REQUEST'
export const TRANSACTION_ADD_SUCCESS = 'TRANSACTION_ADD_SUCCESS'
export const TRANSACTION_ADD_FAIL = 'TRANSACTION_ADD_FAIL'
export const TRANSACTION_ADD_RESET = 'TRANSACTION_ADD_RESET'
